[PRMT-819] Setup DNS and NLB for HSCN and PTL-env
- Change DNS zones and records so that we can register
mhs-inbound-test-x26.mhs.patient-deductions.nhs.uk on HSCN DNS'es which
is a domain name compliant with NHS'es policy
- Protect against NLB being accidentally deleted. It would cause IPs on
HSCN to change and requires to register DNS names, manually, again.
 - Added names to LB target groups

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -5,6 +5,8 @@ set -Eeo pipefail
 NHS_SERVICE=mhs
 AWS_REGION=eu-west-2
 
+CERTIFICATES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/mhs-certs"
+
 if [ -z "${MHS_IMAGE_TAG}" ]; then
   MHS_IMAGE_TAG="${GO_REVISION_INTEGRATION_ADAPTORS:-alpha}"
 fi
@@ -66,6 +68,57 @@ function generate_ssh_key {
    --value "`cat ${ssh_directory}/id_rsa`"
 }
 
+
+function generate_csr {
+  keys_file_name="$1"
+  # If you intend to secure the URL https://www.yourdomain.com, then your CSR’s common name must be www.yourdomain.com
+  common_name="$2"
+  fqdn=$common_name
+
+  if [[ -z "$keys_file_name" ]]; then
+    echo "Keys filename missing"
+    exit 1
+  fi
+  if [[ -z "$common_name" ]]; then
+    echo "domain name missing"
+    exit 1
+  fi
+
+  echo "Preparing certificates for: ${keys_file_name} on ${fqdn}, common_name: ${common_name}"
+  mkdir -p $CERTIFICATES_DIR
+
+  # 1. Create a config file for generating a Certificate Signing Request (CSR).
+  cat <<EOF >${CERTIFICATES_DIR}/csr.conf
+[ req ]
+default_bits = 2048
+prompt = no
+default_md = sha256
+req_extensions = req_ext
+distinguished_name = dn
+
+[ dn ]
+CN = ${common_name}
+
+[ req_ext ]
+subjectAltName = @alt_names
+
+[ alt_names ]
+DNS.1 = ${fqdn}
+
+[ v3_ext ]
+authorityKeyIdentifier=keyid,issuer:always
+basicConstraints=CA:FALSE
+keyUsage=keyEncipherment,dataEncipherment
+extendedKeyUsage=serverAuth,clientAuth
+subjectAltName=@alt_names
+EOF
+
+  # 2. Create a private key (${keys_file_name}.key) and then generate a certificate request (${keys_file_name}.csr) from it.
+  # https://www.openssl.org/docs/manmaster/man1/req.html
+  openssl genrsa -out ${keys_file_name}.key 2048
+  openssl req -new -key ${keys_file_name}.key -out ${keys_file_name}.csr -config ${CERTIFICATES_DIR}/csr.conf
+}
+
 command="$1"
 case "${command}" in
   _ssh_key)
@@ -116,6 +169,13 @@ case "${command}" in
       ;;
   generate_certs)
       dojo "./tasks _generate_certs"
+      ;;
+  _csr)
+      check_env
+      fqdn="mhs-inbound-$NHS_ENVIRONMENT-x26.mhs.patient-deductions.nhs.uk"
+      generate_csr "mhs-inbound-$NHS_ENVIRONMENT-x26" $fqdn
+      echo "The CSR has to be sent together with endpoint registration. Use the form below or ask endpoint admin to register it"
+      echo "https://digital.nhs.uk/forms/combined-endpoint-and-service-registration-request"
       ;;
   _upload_certs)
       if [ "${NHS_ENVIRONMENT}" == "dev" ]; then
